# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "50d2bcc1c878d8c6c746005bc927db35"
name = "zync-app"
handle = "zync-app"
application_url = "https://pipe-emissions-retail-models.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://pipe-emissions-retail-models.trycloudflare.com/auth/callback",
  "https://pipe-emissions-retail-models.trycloudflare.com/auth/shopify/callback",
  "https://pipe-emissions-retail-models.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
